// Mots à deviner : des mots courants, sans accents. Ils sont triés par longueur au chargement
// et seuls ceux présents dans le dictionnaire sont gardés (motus.js).
export const SOLUTIONS = `ABEILLE ABRICOT ABRIS ACCUEIL ACIER ACTEUR ADIEU ADRESSE AFFAIRE AFFICHE AGENCE AGENT AIGUILLE
AIMER ALBUM ALBUMS ALLER ALLUMER AMITIE AMOUR ANCIENS ANGLE ANIMAL ANIMAUX ANNEE APPEL ARBRE ARBRES
ARCHIVE ARGENT ARRIVE ARTICLE ASILE ATELIER ATOUT AUTEUR AVENIR AVENTURE AVION AVOCAT BAGAGE
BAGARRE BALANCE BALCON BALEINE BALLE BANANE BANDE BANQUE BARBE BASKET BATEAU BATON BATTERIE BEAUTE
BESOIN BETAIL BEURRE BIBLIOTHEQUE BIERE BIJOU BILAN BILLET BISCUIT BISOUS BLANC BLEUE BOIRE BONNE
BOUCHE BOUGIE BOUQUET BOUTEILLE BOUTON BRIGADE BRIQUE BROCHURE BRUIT BUREAU CABANE CABLE CADEAU
CADRE CAFES CAHIER CALME CAMION CAMPING CANAL CANARD CAPITAL CARNAVAL CARTE CARTON CASTING CERISE
CERVEAU CHAIR CHAISE CHAMBRE CHAMP CHANCE CHANT CHAPEAU CHARGE CHASSE CHATEAU CHAUD CHAUSSON CHEMIN
CHEMISE CHEVAL CHIEN CHIFFRE CHOSE CIDRE CINEMA CITOYEN CITRON CLAIR CLASSE CLIENT CLIMATS COCHON
COEUR COLERE COLLEGE COLLINE COMBAT COMPTE COMPTOIR COMTE CONCERT CONSEIL CONTRAT COPAIN CORPS
COSTUME COUPABLE COUPE COURAGE COURS COUSIN COUVERT CRANE CRAVATE CRAYON CREME CRISE CRISTAL CROSSE
CUISINE CULTURE CYCLE DANGER DANSE DANSEUR DEBUT DELAI DENTS DEPART DESERT DESSERT DESSIN DIAMANT
DIMANCHE DIPLOME DOCTEUR DOMAINE DOSSIER DOUCHE DROIT ECHARPE ECHECS ECOLE ECOLIER ECRAN ECUREUIL
EFFET EGLISE ELEVE ELEVES EMOTION ENERGIE ENFANT ENNEMI ENTENTE ENTRE EPAULE EPISODE EQUIPE
ESCALIER ESPACE ESSAI ETAGE ETOILE ETUDES ETUDIANT FABLE FACON FAIRE FAMILLE FANTOME FARCE FAUTEUIL
FENETRE FERME FERMIER FESTIVAL FETES FIBRE FICHIER FIGURE FILLE FINAL FLECHE FLEUR FOLIES FONTAINE
FORCE FORET FORME FORMULE FRAIS FRAISE FRERE FROMAGE FRUIT FUMEUR GAGNANT GALAXIE GALERIE GARAGE
GARCON GARDE GATEAU GENOUX GENRE GESTE GIRAFE GLACE GLACON GRAIN GRAINE GRAND GRENADE GRENIER
GUERRE GUIDE GUITARE HABIT HABITANT HAMEAU HERBE HEURE HISTOIRE HIVER HOMARD HOMME HONNEUR HOPITAL
HORLOGE HOTEL HUMIDITE HUMOUR IDEAL IMAGE ISLAND JARDIN JAUNE JOUER JOUET JOUEUR JOURNAL JUPES
JUSTICE LAINE LAMPE LANTERNE LAPIN LAPINS LARGE LECTEUR LECTURE LEGUME LETTRE LIBERTE LIVRE LOCAL
LONGS LUMIERE LUNDI LUNETTE MACHINE MAGASIN MAGIE MAIRE MAISON MALADE MANGE MANTEAU MARCHAND MARCHE
MARDI MARIAGE MATCH MATELAS MATINEE MEDAILLE MEDECIN MELODIE MEMOIRE MENTHE MERCI MESSAGE METIER
METRO MIEUX MINUTES MIROIR MISSION MOMENT MONDE MONTRE MOTEUR MOULIN MOUSTIQUE MOUTON MOYEN MUSEE
MUSIQUE NAGER NATURE NAVIRE NEIGE NIVEAU NOIRE NOMBRE NUAGE NUMERO OBJECTIF OCEAN OCTOBRE OISEAU
OMBRE ONCLE ORAGE ORAGEUX ORANGE ORCHESTRE ORDRE ORDRES OREILLE OUTIL PAGES PANIER PAPIER PAPILLON
PARAPLUIE PARCOURS PARENT PARIS PAROLE PARTI PASSAGE PASSION PATIENCE PATRON PATTE PAUSE PAYSAGE
PAYSAN PECHE PEINE PEINTURE PENSEE PERLE PERSONNE PETIT PHOTO PHRASE PIANO PIECE PIERRE PILOTE
PINGOUIN PISTE PLACARD PLACE PLAGE PLANETE PLANS PLUIE PLUMES POCHE POIDS POINT POISSON POITRINE
POLITIQUE POMME POMPIER PORTE PORTRAIT POSTE POUCE POULAIN POULET PREMIER PRESSE PRESSION PRINCE
PRINTEMPS PRISE PRIX PROBLEME PROJET PROMENADE PROPRE PUBLIC QUAIS QUALITE QUARTIER RACLETTE
RADIATEUR RADIO RAISON RANGE RAPIDE RECETTE RECHERCHE RECIT REGARD REGLE REINE REPAS REPONSE
REQUETE REQUIN RESEAU RESTE REVEIL REVES RICHE RIDEAU RIVAL RIVIERE ROBOT ROMANCE ROSEAU ROUGE
ROUTE RUBAN SABLE SAINT SAISON SALADE SALLE SALON SAUCE SAUCISSE SAUMON SCENE SCIENCE SECRET SECTE
SELLE SEMAINE SENTIER SERPENT SERRE SERVICE SIESTE SIGNE SILENCE SINGE SITES SOCIETE SOLDATS SOLDE
SOLEIL SOMME SOURIS SOUVENIR SPECTACLE SPORT SPORTIF STADE STATION STATUE STYLO SUCCES SUCRE SUITE
SURPRISE SYSTEME TABLE TABLEAU TALENT TANTE TARTE TASSE TAUREAU TAXIS TEMPETE TEMPS TENNIS TERRAIN
TERRE TEXTE THEATRE TICKET TIGRE TIROIR TITRE TOMATE TOMBE TONNEAU TORNADE TORTUE TOUCHE TOUR TRAIN
TRAIT TRAJET TRAVAIL TRESOR TRIBUNE TROMPETTE TROUPEAU TRUCS TRUFFE TUILE TUNNEL UNION UNIVERS
USINE VACANCE VAGUE VAISSEAU VALISE VALSE VAMPIRE VAPEUR VENDEUR VENTILATEUR VERRE VERSION VESTE
VICTOIRE VIDEO VILLAGE VILLE VIOLON VISAGE VITESSE VITRE VOEUX VOILE VOISIN VOITURE VOLCAN VOLCANS
VOTRE VOYAGE ZEBRE`;
